language: node_js
node_js:
  - "10.15.1"
addons:
  postgresql: "9.5"
services:
  - postgresql
install:
  - yarn
before_script:
  - export PGHOST=localhost
  - export PGDATABASE=queue
  - export PGUSER=postgres
  - export PGPASSWORD=
  - createdb $PGDATABASE
script:
  - npm run test
